= Preface

*[red]#TODO: Replace the code examples below with code examples from this book.#*

We use a number of typographical conventions within this book that distinguish between different kinds of information.

Code in the text, including commands, variables, file names, CSS class names, and property names are shown as follows:
"Spring Boot uses a `public static void main` entry-point that launches an embedded web server for you."

A block of code is set out as follows. It may be colored, depending on the format in which you're reading this book.

[source,html]
.src/main/webapp/form.html
----
<form ng-submit="search()">
    <input type="search" name="search" ng-model="term">
    <button>Search</button>
</form>
----

[source,java]
.src/main/java/demo/DemoApplication.java
----
@RestController
class BlogController {

    @RequestMapping("/blogs")
    Collection<Blog> list() {
        return repository.findAll();
    }

    @Autowired
    BlogRepository repository;
}
----

When we want to draw your attention to a particular part of the code, it's called out with numbers.

[source,javascript]
----
.controller('SearchController', function ($scope, SearchService) { <1>
    $scope.search = function () { <2>
        console.log("Search term is: " + $scope.term); <3>
        SearchService.query($scope.term).then(function (response) {
            $scope.searchResults = response.data;
        });
    };
})
----
<1> To inject `SearchService` into `SearchController`, simply add it as a parameter to the controller's argument list.
<2> `$scope.search()` is a function that's called from the HTML's `<form>`, wired up using the `ng-submit` directive.
<3> `$scope.term` is a variable that's wired to `<input>` using the `ng-model` directive.

NOTE: General notes are shown using callouts like this.

TIP: Tips are shown using callouts like this.

IMPORTANT: Relevant comments are shown using callouts like this.

CAUTION: Comments to bear in mind are shown using callouts like this.

WARNING: Warnings are shown using callouts like this.

.Sidebar
****
Additional information about some topics may be displayed using a sidebar like this.
****

Finally, this text shows what a quote looks like.

"In the end, it's not the years in your life that count. It's the life in your years."
-- Abraham Lincoln

"El secreto de una buena vejez no es otra cosa que un pacto honrado con la soledad."
-- Gabriel García Márquez (1927-2014) Escritor colombiano.

== Reader feedback

We always welcome feedback from our readers. Let us know what you think about this book — what you liked or disliked. 
Reader feedback helps us develop titles that you get the most out of. 
To send us feedback, e-mail us at carlosaortiz@yahoo.com. 

If you have a topic that you have expertise in and you are interested in either writing or contributing send an email to carlosaortiz@yahoo.com.
