= Tips and Tricks
In this section you will find anything that is useful to the project and
it is a log for knowledge and a reference as well.

== Gradle
Getting Started With Gradle: Introduction
https://www.petrikainulainen.net/programming/gradle/getting-started-with-gradle-introduction/

Getting Started With Gradle: Our First Java Project
https://www.petrikainulainen.net/programming/gradle/getting-started-with-gradle-our-first-java-project/

Getting Started With Gradle: Creating a Spring Boot Web Application.
https://www.petrikainulainen.net/programming/gradle/getting-started-with-gradle-creating-a-spring-boot-web-application-project/

Using the Gradle build system in the Eclipse IDE - Tutorial
http://www.vogella.com/tutorials/EclipseGradle/article.html

Compile gradle project with another project as a dependency
https://looksok.wordpress.com/2014/07/12/compile-gradle-project-with-another-project-as-a-dependency/

Gradle Include Dependency on another Project and Execution Order
http://www.concretepage.com/build-tools/gradle/gradle-include-dependency-on-another-project-execution-order

NOTE: The Gradle Include Dependency on another Project and Execution Order has a ZIP for source code
for you to learn and use.

== MapStruct
Use of Mapstruct is pending due to time constraints.

NOTE: To be added in the future. For the time being the mappers is in the package mapper and 
they are written manually, for now.

Using MapStruct with Gradle
http://mapstruct.org/news/2013-07-08-using-mapstruct-with-gradle/

MapStruct Reference Guide
http://mapstruct.org/documentation/reference-guide/

Mapstruct Examples
https://github.com/mapstruct/mapstruct-examples

== Unit Testing 
The Benefits of Using assertThat over other Assert Methods in Unit Tests
https://objectpartners.com/2013/09/18/the-benefits-of-using-assertthat-over-other-assert-methods-in-unit-tests/

AssertJ
Fluent assertions for java
http://joel-costigliola.github.io/assertj/

MOCKING IN UNIT TESTS WITH MOCKITO
https://springframework.guru/mocking-unit-tests-mockito/

MOCKITO MOCK VS SPY IN SPRING BOOT TESTS
https://springframework.guru/mockito-mock-vs-spy-in-spring-boot-tests/